### ISSUE TITLE
PeersManager.py line 52 "error: (10022, 'An invalid argument was supplied')"

### ISSUE THREAD

**Issue by FrozenFighter** [gallexis/pytorrent#2]
I have problems using torrent client.
I have tried many torrent files but it has same error.
<img width="424" alt="a" src="https://cloud.githubusercontent.com/assets/9080908/24328475/184ac68a-1215-11e7-9564-a3ffc7ffb562.png">

Thanks

**Comment by FrozenFighter** [comment]
I have tried to run in debian 8 it works perfectly, but unfortunately it dosn't work in windows.
<img width="960" alt="capturae" src="https://cloud.githubusercontent.com/assets/9080908/24328645/fd9fa572-1218-11e7-8c48-82c8390dc6a0.PNG">

How do I know when it finish download or its percent?
Where download files store?

**Comment by gallexis** [comment]
Hi, you have this error because the "select" function is not working on windows, only on unix like: [python-select-select-on-windows](http://stackoverflow.com/questions/22251809/python-select-select-on-windows).
You can try to replace the select with a new thread that will manage the sockets, as explained on the link I gave you.

**Comment by gallexis** [comment]
On the run.py file, line 72, you have this line:
`print "Number of peers: ",len(self.peersManager.unchokedPeers)," Completed: ",float((float(b) / self.torrent.totalLength)*100),"%"`
which give you the number of connected peers, plus the percentage completed, it's enabled by default I think, maybe you don't see it because there is too much debug text.

**Comment by gallexis** [comment]
And the files are downloaded in the same path as your python script is.

**Comment by gallexis** [comment]
I've modified a little the code, and the read me, it looks like it connects to peers, but failed when trying to download data from a peer.

**Comment by FrozenFighter** [comment]
It doesn't seem work for me. I don't think it download any thing, just connect to peer.
<img width="960" alt="e" src="https://cloud.githubusercontent.com/assets/9080908/24330588/7e1a7c5e-124b-11e7-8559-c4c5629d6627.PNG">

**Comment by gallexis** [comment]
Yes same for me, something might have change in the protocol because it worked for me last year, do you have time to figure it out?

**Comment by FrozenFighter** [comment]
I don't think protocol has been change. I have tried older version of your work and it work fine.
https://github.com/gallexis/pytorrent/tree/43389992ffa5673fa36fab1c8336083279b84438
<img width="960" alt="3" src="https://cloud.githubusercontent.com/assets/9080908/24330734/42be6766-124f-11e7-9855-2dfc52a0bf68.PNG">
I think something wrong during update you work.

**Comment by gallexis** [comment]
ok thanks i'll try to figure it out

**Comment by FrozenFighter** [comment]
I have tried all version.
This is lastest version that work fine -> https://github.com/gallexis/pytorrent/commit/a211b22b3f1848f8053124a02fc614e46aca2f1f

So the cause of problems should be in this commit-> https://github.com/gallexis/pytorrent/commit/eb7410c9a2f6d9dc03d5de67fe60be4f81bd1b9a

**Comment by gallexis** [comment]
Ok thanks, I corrected the problem and pushed my commit. I was able to download a torrent, tell me if it works for you.

**Comment by FrozenFighter** [comment]
It works perfectly for me. Thank you for your hard work.
